version: "3"
services:
  server:
    build: server/
    command: node ./src/index.js 
    ports:
      - "3000:3000"
   
  client:
    build: client/
    ports:
      - "8090:8090"
    depends_on:
      - server